### ISSUE TITLE
Can't install the module and not recognized by Appcelerator Studio

### ISSUE THREAD

**Issue by timoa** [falkolab/Ti.RateMe#1]
Hi!

Thank you for this module!

I tried to install it with gittio and it didn't found any suitable module to install...

I downloaded the module and tried to create the following structure:
modules/commonjs/com.falkolab.rateme/1.0.0/package.json

But I get this error after TiStudio detected the module and I saved the tiapp.xml:

```
[WARN] :   Could not find a valid Titanium module id=com.falkolab.rateme version=latest platform=commonjs deploy-type=development
[ERROR] :  Could not find all required Titanium Modules:
[ERROR] :     id: com.falkolab.rateme    version: latest     platform: commonjs  deploy-type: development
```

If you have any tips to solve this :)

Thanks!

**Comment by falkolab** [comment]
Omg. I will fix it now!

**Comment by falkolab** [comment]
I updated module with same version. Please remove installed version from your project and install from github release page.

**Comment by timoa** [comment]
Thank you for your quick reply!

Nothing changed on Github... Last commit 23 hours ago. Same issue for me:
`$ gittio install com.falkolab.rateme`

```
[INFO]  com.falkolab.rateme searching...
[ERROR] com.falkolab.rateme:commonjs no distributable available
[ERROR] com.falkolab.rateme:android no distributable available
[ERROR] com.falkolab.rateme:ios no distributable available
```

If I install the module with AppcStudio, it unzip it on the root of the project, not in the modules folder with the right type of module / version like:
modules/commonjs/[module name]/[version]/

Have you pushed something on Github?

**Comment by falkolab** [comment]
No, I only uploaded fixed package here https://github.com/falkolab/Ti.RateMe/releases
Please download and extract it and replace module in your project.
