### ISSUE TITLE
Nothing happen at start...

### ISSUE THREAD

**Issue by timoa** [falkolab/Ti.RateMe#2]
Hello!

Sorry, but when I installed the module (1.0.0 and this morning 1.0.1) and add this code to my first controller, nothing happens after few minutes...

```
var rateme = require('com.falkolab.rateme');
rateme.init({
    promptDelay: 0, // seconds
    timerInterval: 60, // seconds
    timeUntilPrompt: 7 * 24 * 60 * 60, // 7 days in seconds
    showIfAppHasCrashed: ENV_PRODUCTION ? false : true,
    launchesUntilPrompt: 0
});
```

I try to call directly the rate function but still the same...
`rateme.rate();`

Do I need to use the custom controller like in your example or the default one works for you?

Thank you!

**Comment by falkolab** [comment]
I will try now

**Comment by falkolab** [comment]
Try to close app, clear app data and run again. Maybe it already flagged as rated.

**Comment by timoa** [comment]
I just tried and same issue. I will add more console.log to see the value of the Ti.App.Properties and probably a debug mode can be good to add when you have a lot of other data you want to keep when you test it (login credentials, user preferences, etc.)

I will try to do a PR this weekend if I found the time to do it :)

**Comment by timoa** [comment]
I think that I get this error after I call the rate function:

```
[[INFO] :   RATEME: Init
[INFO] :   2016-03-18 07:44:30.970 CI Remote[31368:15519183] LaunchServices: ERROR: There is no registered handler for URL scheme itms-apps](url)
```

Probably, I need to test it only on a device? The App Store is not present on the simulator

**Comment by falkolab** [comment]
I think yes. I tested now with your config and it work in Android emulator. Remember about `OFF_KEY`

**Comment by falkolab** [comment]
And maybe you need to set `launchesUntilPrompt` to something like 999 or omit it. But Rate Dualog will be shown immediately after the start if you set it to 0.

**Comment by falkolab** [comment]
Do you still have this issue?

**Comment by timoa** [comment]
I will update you when I can rework on it. Probably during this weekend.

**Comment by timoa** [comment]
Hi @falkolab!

I retried this evening and it works for me :) I removed a previous rating widget that conflict with your lib.

Thank you for your help!

Damien

**Comment by falkolab** [comment]
I'm glad to hear it :)
